---
driver:
  name: vagrant

platforms:
- name: windows_2012_r2_virtualbox
  driver:
    name: vagrant_provision
  driver_config:
    box: windows_2012_r2_virtualbox
    guest: :windows
    use_vagrant_provision: true
    vagrantfile_erb: Vagrantfile-windows-chef.erb

suites:
  - name: iis
    run_list:
    attributes:
